AnnaTetjorin/GardenProject

src/App.jsx
=> new branch

src/main.jsx
изменила путь чтобы проект открывался по умолчанию на MainPage
=> Router path MainPage changed

src/Components/Sales/Sales.jsx
Create shaffle for array sales
=> Create random sales shuffle

src/Components/Sales/Sales.module.css
=> fix sales block height

package-lock.json, package.json, src/App.jsx, src/Components/AllCategories/AllCategories.jsx, src/Components/SingleCategoryPage/SingleCategoryPage.jsx, src/Components/SingleCategoryPage/SingleCategoryPage.module.css, src/main.jsx
=> sync repository

src/Components/FilterBar/FilterBar.jsx, src/Components/ProductsCard/ProductsCard.jsx, src/Components/ProductsList/ProductsList.jsx, src/Components/ProductsList/ProductsList.module.css, src/Pages/AllSalesPage.jsx, src/Pages/ProductsPage.jsx
Я изменила стейт products когда диспатчится экшн  из фильтр бара и прописала такую же логику в компоненте All Sales Page и добавила условие чтобы чек бокс не отображался на странице AllSales.
=> make changes in products components&filterBar

src/Components/DataUserForm/DataUserForm.module.css, src/Components/SingleProduct/SingleProduct.jsx, src/Components/SingleProduct/SingleProduct.module.css, src/Components/SingleProduct/SingleProductItems.jsx
SingleProduct ready, SingleSale ready, Form css ready
=> fix SingleProduct SingleSale and DataUserForm

src/Components/Categories/Categories.jsx, src/Components/FilterBar/FilterBar.jsx, src/Components/Sales/Sales.jsx, src/Components/SingleCategoryPage/SingleCategoryPage.jsx, src/layout/Footer/Footer.jsx, src/layout/Footer/Footer.module.css
change tag&style in Footer & add component ProductsCard in Sales & SingleCategoryPage
=> change tag&style in Footer & add component ProductsCard in Sales

src/Components/SingleCategoryPage/SingleCategoryPage.jsx
=> git fix title

src/Components/AllCategories/AllCategories.jsx, src/Components/AllCategories/AllCategories.module.css, src/Components/Button/Button.module.css, src/Components/Categories/Categories.module.css, src/Components/MainBanner/MainBanner.jsx, src/Components/MainBanner/MainBanner.module.css, src/Components/SingleCategoryPage/SingleCategoryPage.module.css, src/layout/Header/Header.jsx, src/layout/Header/Header.module.css
=> burger menu fix, MainBanner button fix

src/Components/AllCategories/AllCategories.jsx, src/Components/BreadCrumbs/BreadCrumbs.jsx, src/Components/BreadCrumbs/BreadCrumbs.module.css, src/Components/SingleProduct/CounterForProduct.jsx, src/Components/SingleProduct/SingleProduct.jsx, src/Components/SingleProduct/SingleProduct.module.css
=> css breadcrumbs

src/Components/ProductsCard/ProductsCard.jsx, src/Components/SingleProduct/SingleProduct.jsx, src/slices/likedProductsSlice.js
=> fix productCart btn add to cart

src/Components/SingleProduct/SingleProduct.jsx, src/Components/SingleProduct/SingleProduct.module.css, src/layout/Header/Header.module.css
create popup for ImageSingleProduct
=> create popup for ImageSingleProduct

src/Components/DiscountModal/DiscountModal.jsx, src/Pages/AllSalesPage.jsx, src/Pages/AllSalesPage.module.css, src/Pages/CategoriesPage.jsx, src/Pages/CategoriesPage.module.css, src/Pages/LikedProductsPage.jsx, src/Pages/LikedProductsPage.module.css, src/Pages/ProductsPage.jsx, src/Pages/ProductsPage.module.css, src/layout/Header/Header.jsx
create Skeleton for AllSales&ProductsPage&LikedProducts&CategoriesPage
=> create Skeleton for AllSales&ProductsPage&LikedProducts&CategoriesPage

src/Components/Cart/Cart.jsx, src/Components/DiscountModal/DiscountModal.jsx, src/Pages/AllSalesPage.jsx, src/Pages/AllSalesPage.module.css, src/Pages/CategoriesPage.jsx, src/Pages/CategoriesPage.module.css, src/Pages/LikedProductsPage.jsx, src/Pages/LikedProductsPage.module.css, src/Pages/ProductsPage.jsx, src/Pages/ProductsPage.module.css, src/layout/Header/Header.jsx, src/slices/cartSlice.js, src/slices/likedProductsSlice.js
create localstorage for cartSlice&likedProductsSlice
=> create localstorage for cartSlice&likedProductsSlice

src/Components/ProductsCard/ProductsCard.jsx, src/slices/cartSlice.js, src/slices/likedProductsSlice.js
=> local storage cart

src/Components/Cart/Cart.jsx
=> add local to card btn

src/Components/SingleProduct/SingleProduct.jsx
add to card function single prod
=> add single product local on btn add to card

src/Components/BreadCrumbs/BreadCrumbs.jsx, src/Components/BreadCrumbs/BreadCrumbs.module.css, src/Components/Categories/Categories.module.css, src/Components/DataUserForm/DataUserForm.jsx, src/Components/DataUserForm/DataUserForm.module.css, src/Components/FilterBar/FilterBar.module.css, src/Components/ProductsCard/ProductsCard.module.css, src/Components/Sales/Sales.module.css, src/Components/TitleBar/TitleBar.module.css, src/Pages/LikedProductsPage.jsx, src/Pages/LikedProductsPage.module.css, src/Pages/ProductsPage.jsx
=> refactory some style

src/Components/BreadCrumbs/BreadCrumbs.module.css, src/Components/Categories/Categories.module.css, src/Components/FilterBar/FilterBar.module.css, src/Components/ProductsCard/ProductsCard.module.css, src/Components/ProductsList/ProductsList.module.css, src/Components/TitleBar/TitleBar.module.css, src/Pages/LikedProductsPage.module.css, src/layout/Header/Header.jsx
=> create new style

src/Components/ProductsList/ProductsList.jsx, src/UI/Pagination.jsx
edit Pagination component&ProductsList
=> edit Pagination component&ProductsList
